name: Post pull request comment

on:
  workflow_run:
    workflows: [Tests]
    types: [completed]

jobs:
  post_pr_comment:
    uses: BMCV/github-workflows/.github/workflows/coverage-post-pr-comment.yml@main
    secrets:
      github-auth: ${{ secrets.GITHUB_TOKEN }}
