name: Test suite

on:
  workflow_dispatch:
  push:
    branches: ['master']
  pull_request:
    branches: ['*']

jobs:
  run_tests:
    name: Tests
    uses: BMCV/github-workflows/.github/workflows/coverage-run.yml@main
    with:
      main_branch: master
      python_versions: '["3.9", "3.10", "3.11", "3.12"]'
      main_python_version: "3.10"  # report test coverage using Python 3.10, since Python 3.9 skips the `test_textual` tests
      gist-id: 5f8b1433a1c405da22639f817d6a38d9
      gist-filename: repype.json
      run: |
        coverage run -m unittest discover
        coverage combine
        coverage json --omit "tests/*","repype/textual/demo.py"
      env: '{"REPYPE_WATCHDOG_TIMEOUT": 1}'
    secrets:
      gist-auth: ${{ secrets.GIST_SECRET }}
